{
    'name' : 'Air Import',
    'version' : '1.0.0',
    'author' : 'afzalhussainj',
    'sequence' : -100,
    'website' : 'www.instagram.com/afzalhussainj',
    'category' : 'Logistic Management',
    'summary' : 'For managing air imports in logistic',
    'description' : 'For managing air imports in logistic',
    'application' : True,
    'lisence' : 'LGPL-3',
    'depends': [],
    'data': [
        'views/MasterBL.xml',
        'views/hawb.xml',
        'security/ir.model.access.csv',
        'views/ForeignAgent.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
}